/// This file is generated by Weaver 0.10.3
/// DO NOT EDIT!
// MARK: - FooTest17
protocol FooTest17DependencyResolver {
    var fee: FeeTest17Protocol { get }
}
final class FooTest17DependencyContainer: FooTest17DependencyResolver {
    private var _fee: FeeTest17Protocol?
    var fee: FeeTest17Protocol {
        if let value = _fee { return value }
        let value = FeeTest17()
        _fee = value
        return value
    }
    init() {
        _ = fee
    }
}
// MARK: - FuuTest17
protocol FuuTest17InputDependencyResolver {
    var fee1: FeeTest17Protocol { get }
}
protocol FuuTest17DependencyResolver {
    var fee1: FeeTest17Protocol { get }
}
final class FuuTest17DependencyContainer: FuuTest17DependencyResolver {
    let fee1: FeeTest17Protocol
    init(injecting dependencies: FuuTest17InputDependencyResolver) {
        fee1 = dependencies.fee1
    }
}
